version: '3.8'

services:
  api:
    build:
      context: ./signrhflow-api
      dockerfile: Dockerfile
    container_name: signrhflow_api
    ports:
      - "8000:8000"
    volumes:
      - ./signrhflow-api:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - signrhflow-network

  queue:
    build:
      context: ./signrhflow-api
      dockerfile: Dockerfile
    container_name: signrhflow_queue
    working_dir: /var/www/html
    command: php artisan queue:work --queue=contracts,webhooks --tries=5 --sleep=1
    volumes:
      - ./signrhflow-api:/var/www/html
    depends_on:
      - api
      - redis
      - db
    networks:
      - signrhflow-network

  web:
    image: node:20
    container_name: signrhflow_web
    working_dir: /app
    volumes:
      - ./signrhflow-web:/app
    ports:
      - "4200:4200"
    command: bash -c "npm install && npx ng serve --host 0.0.0.0 --poll 2000"
    networks:
      - signrhflow-network

  db:
    image: postgres:16-alpine
    container_name: signrhflow_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: signrhflow
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - signrhflow-db-data:/var/lib/postgresql/data
    networks:
      - signrhflow-network

  redis:
    image: redis:7-alpine
    container_name: signrhflow_redis
    ports:
      - "6379:6379"
    volumes:
      - signrhflow-redis-data:/data
    networks:
      - signrhflow-network

networks:
  signrhflow-network:
    driver: bridge

volumes:
  signrhflow-db-data:
  signrhflow-redis-data: