server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /SignRhFlow/ {
        try_files $uri $uri/ /SignRhFlow/index.html;
    }

    location = /SignRhFlow {
        return 301 /SignRhFlow/;
    }
}
